#!/bin/bash
#simply
echo "hello"
val=$(cat /sys/class/backlight/intel_backlight/brightness)
if [ "$1" = "+" ] ; then
  val=`expr $val + 100`
else
  val=`expr $val - 100`
  if [ $val -le 0 ];then
    val=0
  fi
fi
echo $val | tee /sys/class/backlight/intel_backlight/brightness
#num=`expr $num + 50`
#echo $num > /sys/class/backlight/intel_backlight/brightness
